config/routes.rb
TodosApp::Application.routes.draw do

  root to: 'pages#front'
  resources :todos
  resources :sessions, only: [:create]
  resources :users
  get 'sign_out', to: "sessions#destroy"

  namespace :admin do
    resources :todos, only: [:index]
  end

  resources :payments

end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    before_create :generate_token
  end

  private

  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end

end

app/models/credit.rb
class Credit
  attr_accessor :credit_balance, :user

  def initialize(user)
    @credit_balance = user.current_credit_balance
    @user = user
  end

  def -(number)
    credit_balance = credit_balance - number
  end

  def save
    user.current_credit_balance = credit_balance
    user.save
  end

  def depleted?
    credit_balance < 0
  end

  def low_balance?
    credit_balance < 10
  end



end

app/models/stripe_wrapper.rb
module StripeWrapper
  class Charge
    attr_reader :response, :status
    def initialize(response, status)
      @response = response
      @status = status
    end

    def self.create(options={})
      StripeWrapper.set_api_key
      begin
        response = Stripe::Charge.create(amount: options[:amount], currency: 'usd', card: options[:card])
        new(response, :success)
      rescue Stripe::CardError => e
        new(e, :error)
      end
    end

    def successful?
      status == :success
    end

    def error_message
      response.message
    end
  end

  def self.set_api_key
    Stripe.api_key = Rails.env.production? ? ENV['STRIPE_LIVE_API_KEY'] : "sk_test_S7SfOyW1ciRq6DBVsEb7WPRW"
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :todos, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :todo
  belongs_to :tag
end

app/models/todo.rb
# require_relative '../../lib/tokenable'

class Todo < ActiveRecord::Base
  include Tokenable
  has_many :taggings
  has_many :tags, through: :taggings
  validates :name, presence: true
  belongs_to :user
  # validates :description, presence: true


  def name_only?
    description.blank?
  end

  def save_with_tags
    if save
      create_location_tags
      true
    else
      false
    end
  end

  def to_param
    token
  end

  def decorator
    TodoDecorator.new(self)
  end


  private
    def create_location_tags
      location_string = name.slice(/.*\bAT\b(.*)/,1).try(:strip)

      if location_string
        locations = location_string.split(/\,|and/).map(&:strip)
        locations.each do |location|
          tags.create(name: "location:#{location}")
        end
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_level_policy.rb
class UserLevelPolicy
  attr_reader :user

  def initialize(user)
    @user = user
  end

  def premium?
    user.created_at < Date.new(2010, 1, 1) || user.plan.premium?
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/admin/todos_controller.rb
class Admin::TodosController < AdminsController

  def index
    @todos = Todo.all
  end
end

app/controllers/admins_controller.rb
class AdminsController < AuthenticatedController
  before_filter :ensure_admin

  def ensure_admin
    flash[:danger] = "You do not have access to that area."
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def ensure_sign_in
    unless logged_in?
      flash[:danger] = "You are not logged in."
      redirect_to root_path
    end
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_filter :ensure_sign_in


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
    redirect_to todos_path if current_user
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def create
    # Get the credit card details submitted by the form
    token = params[:stripeToken]

    # Create the charge on Stripe's servers - this will charge the user's card
    charge = StripeWrapper::Charge.create( :amount => 1000, :card => token)
      # charge = Stripe::Charge.create(
      #   :amount => 1000, # amount in cents, again
      #   :currency => "usd",
      #   :card => token,
      #   :description => "payinguser@example.com"
      # )
    if charge.successful?
      flash[:success] = "Thank you for your generous support!"
      redirect_to new_payment_path
    else
      flash[:danger] = charge.error_message
      redirect_to new_payment_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.where(username: params[:username]).first
    session[:user_id] = user.id if user
    redirect_to current_user.admin? ?  admin_todos_path : todos_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < AuthenticatedController
  before_filter :ensure_sign_in

  def index
    # @todos = Todo.all
    # @todos = current_user.todos
    @todos = current_user.todos.map(&:decorator)
    @todo = Todo.new
  end

  def new
    @todos = Todo.all
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    # credit = Credit.new(current_user)
    if @todo.save_with_tags
      # if UserLevelPolicy.new(current_user).premium?
        # credit = credit - 1
      # else
        # credit = credit - 2
      # end

      # credit.save

      # if credit.depleted?
          #send insufficient credit email
        # elsif credit.low_laance
          # send low balance email
        # end

      AppMailer.delay.notify_on_new_todo(current_user, @todo)

      flash[:success] = "saved todo"
      redirect_to root_path
    else
      flash[:error] = "not saved"
      render :new
    end
  end

  def show
    @todo = Todo.find_by(token: params[:id])
  end

  private
  def todo_params
    params.require(:todo).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/todos/index.html.haml
= "Hello, #{current_user.full_name} #{link_to 'sign out', sign_out_path}".html_safe
%br
%ul
  - @todos.each do |todo|
    %li= link_to "#{todo.display_text}", todo
    \-

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/front.html.haml
= form_tag sessions_path do
  = label_tag :username, "Username"
  = text_field_tag :username
  %br
  = submit_tag "Sign in", class: "btn"
%br
= link_to "Donate $5", new_payment_path

app/views/payments/new.html.haml
%p Thank you for your support.
/ = form_tag payments_path do
/   %script(src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="pk_test_wUUlTBT8HkbSoT2DcHcE8hYP" data-image="/square-image.png" data-name="Support Todo App" data-description="Thank you for your donation." data-amount="2000")

/ content_for :head do
<script type="text/javascript" src="https://js.stripe.com/v2"></script>
<script type="text/javascript">
Stripe.setPublishableKey('pk_test_wUUlTBT8HkbSoT2DcHcE8hYP');
</script>
# = javascript_include_tag 'payments'


= form_tag payments_path, id: 'payment-form' do
  %fieldset.credit_card
    %span.payment-errors
    %label Credit Card Number
    %input.span3.card-number(type="text")
    %label Security Code
    %input.span3.card-cvc(type="text")
    %label Expiration
    = select_month(Date.today, {add_month_numbers: true}, name: nil, class: 'span card-expiry-month')
    = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, name: nil, class: 'span1 card-expiry-year')
  %fieldset.actions
    = submit_tag "Submit Payment", class: "btn payment_submit"

app/views/todos/index.html.haml
= "Hello, #{current_user.full_name} #{link_to 'sign out', sign_out_path}".html_safe
= form_for(@todo ) do |f|
  = f.label :name, "Name"
  = f.text_field :name, size: "50"
  / = f.text_field :description
  = f.submit "Add Todo"
%br
%ul
  - @todos.each do |todo|
   / %li= link_to "#{todo.display_text}", todo
   / %li= link_to TodoDecorator.new(todo).display_text, todo
    %li= link_to todo.decorator.display_text, todo

app/views/todos/new.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for(@todo, html: { class: "form-horizontal" } ) do |f|
        = f.text_field :name
        = f.text_field :description
        = f.submit "Add Todo"
      %br
      %ul
        - @todos.each do |todo|
          %li= link_to todo.name, todo_path(todo)

app/views/todos/show.html.haml
%h1
  Todos!
%h2
  = @todo.name
%div
  = @todo.display_text